### Indexação e Fatiamento de Arrays

In [2]:
# Fazendo a importação da biblioteca que vamos utilizar
import numpy as np

In [5]:
# Criando um array com o método arange(start, end, step)
arr = np.arange(0, 30, 3); arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [7]:
# Para fazer uma consulta nos elementos do arrays em relação a seu index
arr[4]

12

In [8]:
# Para fazer uma consulta nos elementos do array de uma posição inicial até a final, temos
arr[2:7]

array([ 6,  9, 12, 15, 18])

In [9]:
# Usando difernetes formas para consultar um array
arr[:4]

array([0, 3, 6, 9])

In [10]:
# Usando difernetes formas para consultar um array
arr[4:]

array([12, 15, 18, 21, 24, 27])

In [11]:
# Usando difernetes formas para consultar um array
arr[1:-1:2]

array([ 3,  9, 15, 21])

In [13]:
# Fazendo alterações no array com o método de consulta
arr[4:] = 100; arr

array([  0,   3,   6,   9, 100, 100, 100, 100, 100, 100])

In [16]:
# Criando um array até 50
arr = np.arange(50); arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [18]:
# Vamos converter essa nova variável arr com método reshape()
arr.reshape(5,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [23]:
# Podemos usar o método reshape de uma nova forma mais simplificada
arr = np.arange(0,50,2).reshape(5,5); arr

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48]])

In [24]:
# Usando atributo shape para verificar o tamanho do array e sua dimensão
arr.shape

(5, 5)

In [25]:
# Fazendo uma consulta agora na matriz arr[linha, coluna]
arr[3,0:]

array([30, 32, 34, 36, 38])

In [26]:
# Consultando o array com mesmo resultado mais de duas formas diferentes: Primeira forma
arr[:3,]

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [27]:
# Consultando o array com mesmo resultado mais de duas formas diferentes: Segunda forma arr[linha][coluna]
arr[:3][:]

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [30]:
# Criando um novo array de dados do arr e usando o método copy() para pode manipula=lo sem alterar o dá origem
arr_2 = arr[:3][:].copy(); arr_2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [32]:
# Posso fazer o operações logicas com o array
arr_2 > 15

array([[False, False, False, False, False],
       [False, False, False,  True,  True],
       [ True,  True,  True,  True,  True]])

In [34]:
# Possa manipular o array em forma condicional
bol = arr_2 < 15
arr_2[bol]  # Estou extraindo dados do array arr_2 onde a regra anterior foi satisfeita

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [35]:
# Criando um array de intervalo de 0 a 100 e com 30 elementos
array = np.linspace(0, 100, 30); array

array([  0.        ,   3.44827586,   6.89655172,  10.34482759,
        13.79310345,  17.24137931,  20.68965517,  24.13793103,
        27.5862069 ,  31.03448276,  34.48275862,  37.93103448,
        41.37931034,  44.82758621,  48.27586207,  51.72413793,
        55.17241379,  58.62068966,  62.06896552,  65.51724138,
        68.96551724,  72.4137931 ,  75.86206897,  79.31034483,
        82.75862069,  86.20689655,  89.65517241,  93.10344828,
        96.55172414, 100.        ])

In [36]:
# Verificando o tamanho e a dimensão do array
array.shape

(30,)

In [38]:
# Convertendo o array em uma matriz de dimensão (3, 10)
array = array.reshape(3,10); array

array([[  0.        ,   3.44827586,   6.89655172,  10.34482759,
         13.79310345,  17.24137931,  20.68965517,  24.13793103,
         27.5862069 ,  31.03448276],
       [ 34.48275862,  37.93103448,  41.37931034,  44.82758621,
         48.27586207,  51.72413793,  55.17241379,  58.62068966,
         62.06896552,  65.51724138],
       [ 68.96551724,  72.4137931 ,  75.86206897,  79.31034483,
         82.75862069,  86.20689655,  89.65517241,  93.10344828,
         96.55172414, 100.        ]])

In [39]:
# Verificando o tamanho e a dimensão
array.shape

(3, 10)

In [40]:
# Fazendo uma consulta 
array[:2, 2]

array([ 6.89655172, 41.37931034])