### Criação de Vetores e Arrays e Numpy Random

In [2]:
# Importando a biblioteca que iremos utilizar
import numpy as np

In [3]:
# Criando uma lista 
minha_lista = [1, 2, 3]; minha_lista

[1, 2, 3]

In [8]:
# Convertendo minha lista em um array
np.array(minha_lista)

array([1, 2, 3])

In [10]:
# Criando uma lista de matriz; lista de listas
minha_matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]; minha_matriz

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
# Convetendo minha lista de listas que nesse caso é uma matriz em array
np.array(minha_matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
# Criando um array com o método arange(start, end, step)
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
# Criando um array de zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [17]:
# Adicionado uma variavel para receber a matriz de zeros
arr = np.zeros(4); arr

array([0., 0., 0., 0.])

In [20]:
# Criando uma matriz 5x5 
arr = np.zeros((5,5)); arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
# Criando uma matriz com elementos igual a 1
arr_1 = np.ones((5,5)); arr_1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [25]:
# Criando uma matriz identidade com método eye()
np.eye()

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
# Existe outro metodo de criação de matriz que é o linspace(start, end, step_=mente_espaçados)
# é semelhante ao arange()
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [31]:
# Existe outro metodo de criação de matriz que é o linspace(start, end, step_=mente_espaçados)
# é semelhante ao arange()
np.linspace(0, 10, 6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [32]:
# O random pode criar números aleátorios baseado em regras diferentes e nesse caso são números 
# aleátorios baseados em uma Distribuição uniforme
np.random.rand(5)

array([0.54679716, 0.49478358, 0.08491092, 0.06137442, 0.72029241])

In [33]:
# Para criar uma sequencia de zero a 100, basta multiplicar por 100
np.random.rand(5) * 100

array([88.11242913, 75.84286457, 75.15441856,  3.10475124, 29.33207788])

In [37]:
# Criando uma matriz com o método random seguindo uma distribuição uniforma rand(n_element, dim1, dim2, ...)
np.random.rand(5, 4, 3)

array([[[0.63009973, 0.48890652, 0.44645964],
        [0.53952754, 0.33427989, 0.50694835],
        [0.559113  , 0.28197167, 0.02730171],
        [0.7751145 , 0.82727335, 0.14857224]],

       [[0.79118061, 0.0951136 , 0.53896463],
        [0.95424137, 0.39489939, 0.7374373 ],
        [0.39665247, 0.62607327, 0.66334549],
        [0.76865361, 0.05726485, 0.0710891 ]],

       [[0.32735597, 0.41862525, 0.77612452],
        [0.71604277, 0.12215053, 0.70925803],
        [0.97185274, 0.57732393, 0.13176586],
        [0.00663715, 0.97305417, 0.48165574]],

       [[0.96585355, 0.14455022, 0.71713963],
        [0.60622277, 0.80532238, 0.10995482],
        [0.68245138, 0.23600023, 0.52469871],
        [0.09216864, 0.98630729, 0.74409146]],

       [[0.69759879, 0.5459743 , 0.61187659],
        [0.08225859, 0.69817046, 0.99723722],
        [0.55836637, 0.37028604, 0.72029461],
        [0.37075011, 0.31400152, 0.38730528]]])

In [54]:
# Criando uma sequência aleátoria com números respeitando a distribuição normal com média 0 e desvio padrão 1
np.random.randn(4)

array([-0.13410031,  0.34344   , -0.29133643, -0.17722683])

In [55]:
# Criando números inteiros aleátorios dentro de um intervalo
np.random.randint(0, 100, 10)

array([68, 12, 53, 65, 26, 52,  0, 39,  9, 36])

In [58]:
# Criando a mesma sequência de números aleátorios como utra abordagem
np.round(np.random.rand(5) *100, 0)

array([47., 38., 47.,  7., 39.])

In [60]:
# Criando um array com 25 elementos aleátorios
arr = np.random.rand(25); arr

array([0.09752334, 0.1316389 , 0.21181779, 0.54606563, 0.48512302,
       0.3419177 , 0.94915374, 0.14726467, 0.61906201, 0.72379064,
       0.66417916, 0.52154649, 0.5963514 , 0.81504384, 0.00556962,
       0.31082315, 0.4488967 , 0.05823368, 0.86552512, 0.26984214,
       0.53778975, 0.36232343, 0.8406611 , 0.4108603 , 0.19581881])

In [64]:
# Convertendo a variável arr com método reshape em formato de matriz
arr.reshape((5, 5))

array([[0.09752334, 0.1316389 , 0.21181779, 0.54606563, 0.48512302],
       [0.3419177 , 0.94915374, 0.14726467, 0.61906201, 0.72379064],
       [0.66417916, 0.52154649, 0.5963514 , 0.81504384, 0.00556962],
       [0.31082315, 0.4488967 , 0.05823368, 0.86552512, 0.26984214],
       [0.53778975, 0.36232343, 0.8406611 , 0.4108603 , 0.19581881]])

In [68]:
# Para verificar o tamanho da matriz e suas dimensões usamos o atributo shape()
arr.shape

(5, 5)

In [69]:
# Passando um novo parâmetro de conversão para uma matriz (5,5); só para verificar o 
# tamanho e a dimensão com atributo shape

arr = arr.reshape((5, 5))
arr.shape

(5, 5)

In [70]:
# Usando método max() para verificar o maior número no array
arr.max()

0.949153742662486

In [71]:
# Usando método min() para verificar o menor número no array
arr.min()

0.005569622472919589

In [74]:
# O método argmax() retorna o index do maior elemento
arr.argmax()

6

In [75]:
# O método argmin() retorna o index do menor elemento
arr.argmin()

14